import { UserRole } from '../types/auth';
import { DashboardData } from '../types/dashboard';
import { PaginatedInstruments, Instrument } from '../types/instrument';

export const MOCK_USERS = {
  admin: {
    id: 1,
    name: 'Dr. Sarah Jenkins',
    email: 'admin@nawi-lab.org',
    role: 'admin' as UserRole,
  },
  tester: {
    id: 2,
    name: 'Marcus Vance',
    email: 'tester@nawi-lab.org',
    role: 'tester' as UserRole,
  },
  reviewer: {
    id: 3,
    name: 'Elena Rostova',
    email: 'reviewer@nawi-lab.org',
    role: 'reviewer' as UserRole,
  },
  viewer: {
    id: 4,
    name: 'Arthur Pendelton',
    email: 'viewer@nawi-lab.org',
    role: 'viewer' as UserRole,
  },
};

export const MOCK_DASHBOARD: DashboardData = {
  summary: {
    total_instruments: 4,
    active_instruments: 4,
    tests_in_progress: 3,
    completed_tests: 13,
    tests_pending_review: 1,
    pass_count: 13,
    fail_count: 0,
    reports_generated: 4,
  },
  recent_activity: [
    {
      id: 'act-1',
      type: 'test_submission',
      title: 'TEST-2026-0088 Submitted for Review',
      description: 'Kern Precision Balance 5000g submitted by Marcus Vance',
      timestamp: '10 minutes ago',
      status: 'Under Review',
      badge_variant: 'warning',
    },
    {
      id: 'act-2',
      type: 'report_generation',
      title: 'Certificate REP-2026-0004 Issued',
      description: 'Mettler Toledo XPR205 Analytical Balance certified OIML R-76 Class I',
      timestamp: '1 hour ago',
      status: 'Completed',
      badge_variant: 'success',
    },
    {
      id: 'act-3',
      type: 'compliance_audit',
      title: 'Periodic Calibration Verified',
      description: 'Sartorius Cubis II High Precision Balance evaluated against Table 6 MPE',
      timestamp: '3 hours ago',
      status: 'PASS',
      badge_variant: 'success',
    },
  ],
};

const items: Instrument[] = [
  {
    id: 1,
    instrument_id: 'INST-2026-001',
    manufacturer: 'Mettler Toledo',
    model: 'XPR205 Analytical Balance',
    serial_number: 'MT-9948210',
    instrument_type: 'Electronic Analytical Balance',
    instrument_class: 'Electronic',
    maximum_capacity: 220,
    minimum_capacity: 0.001,
    verification_scale_interval: 0.0001,
    accuracy_class: 'Class I',
    country_of_manufacture: 'Switzerland',
    status: 'Active',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 2,
    instrument_id: 'INST-2026-002',
    manufacturer: 'Sartorius',
    model: 'Cubis II High Precision',
    serial_number: 'SAR-2024-8841',
    instrument_type: 'Precision Balance',
    instrument_class: 'Electronic',
    maximum_capacity: 5200,
    minimum_capacity: 0.05,
    verification_scale_interval: 0.01,
    accuracy_class: 'Class II',
    country_of_manufacture: 'Germany',
    status: 'Active',
    created_at: '2026-01-18T09:30:00Z',
    updated_at: '2026-01-18T09:30:00Z',
  },
  {
    id: 3,
    instrument_id: 'INST-2026-003',
    manufacturer: 'Kern & Sohn',
    model: 'PCB 3500-2 Lab Scale',
    serial_number: 'KERN-771230',
    instrument_type: 'Standard Laboratory Balance',
    instrument_class: 'Electronic',
    maximum_capacity: 3500,
    minimum_capacity: 0.1,
    verification_scale_interval: 0.01,
    accuracy_class: 'Class II',
    country_of_manufacture: 'Germany',
    status: 'Active',
    created_at: '2026-02-01T11:00:00Z',
    updated_at: '2026-02-01T11:00:00Z',
  },
  {
    id: 4,
    instrument_id: 'INST-2026-004',
    manufacturer: 'Ohaus',
    model: 'Defender 5000 Industrial Scale',
    serial_number: 'OH-DEF-5510',
    instrument_type: 'Industrial Bench Scale',
    instrument_class: 'Electromechanical',
    maximum_capacity: 60,
    minimum_capacity: 0.4,
    verification_scale_interval: 0.02,
    accuracy_class: 'Class III',
    country_of_manufacture: 'USA',
    status: 'Active',
    created_at: '2026-02-10T14:15:00Z',
    updated_at: '2026-02-10T14:15:00Z',
  },
];

export const MOCK_INSTRUMENTS: PaginatedInstruments = {
  items,
  total: 4,
  page: 1,
  page_size: 10,
  total_pages: 1,
};
